{{- if .Values.required }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/elasticsearch-operator.openshift-operators-redhat: ""
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: "elasticsearch-operator"
  namespace: "openshift-operators-redhat"
spec:
  channel: "{{ .Values.elasticSearchChannel }}"
  installPlanApproval: "Automatic"
  source: "redhat-operators"
  sourceNamespace: "openshift-marketplace"
  name: "elasticsearch-operator"
{{- end }}
