{{- if .Values.required }}
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - ldap:
      attributes:
        email: []
        id:
        - sAMAccountName
        name:
        - cn
        preferredUsername:
        - sAMAccountName
      bindDN: CN=svcintuser,OU=konsalt,DC=konsalt,DC=info
      bindPassword:
        name: "{{ .Values.SecretName }}"
      insecure: true
      url: ldap://192.168.1.10:389/DC=konsalt,DC=info?sAMAccountName?sub
    mappingMethod: claim
    name: ldap
    type: LDAP
{{- end }}
