apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: 3rd-party-operators
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/m4reshal/GitOps-For-Multi-Openshift-Cluster-Management.git
      revision: HEAD
      directories:
      - path: 3rd-party-operators/*
      - path: 3rd-party-operators/helm-operators/*
      - path: 3rd-party-operators/helm-operators
        exclude: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: 3rd-party-operators
      source:
        repoURL:  https://github.com/m4reshal/example-helm-gitops-practice.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
          - values-ocp.yaml
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          #selfHeal: true
          selfHeal: false
          allowEmpty: true
        syncOptions:
        - ApplyOutOfSyncOnly=true
        retry:
          limit: 15
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 5m
      # Operators
      #        automated:
      #          prune: true
      #        syncOptions:
      #        - Replace=true

