apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/m4reshal/example-helm-gitops-practice.git
      revision: HEAD
      directories:
      - path: core/*
      - path: core/rbac/*
      - path: core/rbac
        exclude: true
      - path: core/jobs/*
      - path: core/jobs
        exclude: true
      - path: core/policies/kyverno-policies/*
      - path: core/policies
        exclude: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: core
      source:
        repoURL: https://github.com/m4reshal/example-helm-gitops-practice.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
          - values-ocp.yaml
      destination:
        server: https://kubernetes.default.svc
      syncPolicy: {}
      # Optional
      #        automated:
      #          prune: true
      #        syncOptions:
      #        - Replace=true
